spring.application.name=s-rest-app

spring.datasource.url=jdbc:postgresql://localhost:5432/youth_leisure_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# update  ? ????????? ????? (?? ??????? ??????). ?????????? ? ??????????.
# validate ? ?????? ?????????, ??? ????? ????????? ? Entity. ?????????? ?? ?????.
# create  ? ??????????? ????? ??? ?????? ??????? (??????? ??? ??????).
# none    ? Hibernate ?????? ?? ?????? ?? ??????.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.connection-init-sql=SET client_encoding TO 'UTF8'