spring.application.name=s-rest-app

spring.datasource.url=jdbc:postgresql://localhost:5432/youth_leisure_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.connection-init-sql=SET client_encoding TO 'UTF8'

jwt.secret=youth-leisure-super-secret-key-2024-ssau
jwt.expiration=86400000